export const STRINGS = {
  searchPlaceholder: 'Search by Title, ISBN, or Author',
  createNewBook: 'Create New Book',
  createBook: 'Create Book',
  updateBook: 'Update Book',
  processing: 'Processing...',
  saving: 'Saving...',
  cancel: 'Cancel',
  confirm: 'Confirm',
  title: 'Title',
  isbn: 'ISBN',
  authors: 'Authors',
  selectOrType: 'Select or type to create new',
  loadingBooks: 'Loading books...',
  edit: 'Edit',
  delete: 'Delete',
  createdBookFeedback: 'Created book successfully',
  updatedBookFeedback: 'Updated book successfully',
  deletedBookFeedback: 'Deleted book successfully',
  confirmDeletion: 'Confirm Deletion',
  deletionCheck: 'Are you sure you want to delete the book',
};
